# Generated by Django 5.0.2 on 2025-06-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consts', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('testCase', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTestCasesExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
    ]
