# Generated by Django 4.2.7 on 2023-11-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0006_contest_question_description_contest_question_lvl_and_more'),
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_test_cases',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question'),
        ),
        migrations.AlterField(
            model_name='sample_test_cases_file',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question'),
        ),
        migrations.AlterField(
            model_name='sample_test_cases_file',
            name='test_case_file',
            field=models.FileField(upload_to='temp_files'),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
