# Generated by Django 4.2.7 on 2023-12-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0009_contest_question_time_limit_and_more'),
        ('Questions', '0002_alter_sample_test_cases_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_test_cases',
            name='explanation',
            field=models.CharField(default='idk what to explain', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample_test_cases',
            name='answer',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sample_test_cases',
            name='sample',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Consttraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consts', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
    ]
