# Generated by Django 4.2.7 on 2024-01-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0014_contests_started_at'),
        ('Questions', '0003_sample_test_cases_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consts', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
        migrations.DeleteModel(
            name='Consttraints',
        ),
    ]
