# Generated by Django 4.2.7 on 2024-01-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0019_remove_contest_question_contest_and_more'),
        ('Questions', '0004_constraints_delete_consttraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('testCase', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
        migrations.RenameModel(
            old_name='sample_test_cases',
            new_name='SampleTestCasesExample',
        ),
        migrations.DeleteModel(
            name='sample_test_cases_file',
        ),
    ]
