# Generated by Django 4.2.7 on 2024-02-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_sampletestcases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletestcasesexample',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sampletestcasesexample',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sampletestcasesexample',
            name='sample',
            field=models.TextField(),
        ),
    ]
