# Generated by Django 5.0.2 on 2025-06-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('lvl', models.CharField(choices=[('EASY', 'EASY'), ('MEDUIM', 'MEDUIM'), ('HARD', 'HARD')], max_length=20)),
                ('point', models.IntegerField()),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField(default=10)),
                ('num_of_test_cases', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('duration', models.DurationField()),
                ('started', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('key', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40)),
                ('tabswitch', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contests')),
            ],
        ),
        migrations.CreateModel(
            name='Contest_submissiosn',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('lang', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=30)),
                ('submit_time', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_groups')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question')),
            ],
        ),
        migrations.AddField(
            model_name='contest_question',
            name='contest',
            field=models.ManyToManyField(to='Contest.contests'),
        ),
    ]
