# Generated by Django 4.2.7 on 2023-11-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_rename_contest_contestants_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_groups',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Contest.contest'),
            preserve_default=False,
        ),
    ]
