# Generated by Django 4.2.7 on 2023-11-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0003_contest_groups_contest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contest',
            new_name='Contests',
        ),
    ]
