# Generated by Django 4.2.7 on 2023-11-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0004_rename_contest_contests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('num_of_test_cases', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contests')),
            ],
        ),
        migrations.AlterField(
            model_name='contest_submissiosn',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest_question'),
        ),
    ]
