# Generated by Django 4.2.7 on 2023-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0005_contest_question_alter_contest_submissiosn_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_question',
            name='description',
            field=models.TextField(default='this desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest_question',
            name='lvl',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDUIM', 'MEDUIM'), ('HARD', 'HARD')], default='EASY', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contests',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
