# Generated by Django 4.2.7 on 2023-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0006_contest_question_description_contest_question_lvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
