# Generated by Django 4.2.7 on 2023-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0009_contest_question_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_submissiosn',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
