# Generated by Django 4.2.7 on 2023-12-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0010_alter_contest_submissiosn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_submissiosn',
            name='lang',
            field=models.CharField(default='python', max_length=10),
            preserve_default=False,
        ),
    ]
