# Generated by Django 4.2.7 on 2023-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0011_contest_submissiosn_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
