# Generated by Django 4.2.7 on 2023-12-11 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0013_contest_question_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
