# Generated by Django 4.2.7 on 2024-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0015_alter_contest_submissiosn_submit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
