# Generated by Django 4.2.7 on 2024-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0017_contests_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='key',
            field=models.TextField(),
        ),
    ]
