# Generated by Django 4.2.7 on 2024-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0018_alter_contests_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_question',
            name='contest',
        ),
        migrations.AlterField(
            model_name='contest_question',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='contest_question',
            name='contest',
            field=models.ManyToManyField(to='Contest.contests'),
        ),
    ]
