# Generated by Django 5.0.2 on 2024-02-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0022_contests_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contestants',
        ),
    ]
